---
title: "Final_quiz_predictionCodes"
author: "wenting"
date: "May 10, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## read data
```{r}
setwd("/Users/Final_Assignment")
training=read.csv("pml-training.csv",sep=",",head=T,stringsAsFactors = F,na.strings=c("","NA"))
testing=read.csv("pml-testing.csv",sep=",",head=T,stringsAsFactors = F,na.strings=c("","NA"))
dim(training)
dim(testing)
```

## remove variables with mostly missing values
```{r}
mostly_data<-apply(!is.na(training),2,sum)>19621
training<-training[,mostly_data]
testing<-testing[,mostly_data]

## remove column that is simply an index, timestamp
training=training[,c(2,8:60)]
testing=testing[,c(2,8:60)]
dim(training)
```

## change variables to numeric and factor
```{r,dependson="createData",echo=FALSE,fig.height=5,fig.width=5}
for (i in 2:53){
	training[,i]=as.numeric(as.character(training[,i]))
}
training$classe=as.factor(as.character(training$classe))
training$user_name=as.factor(as.character(training$user_name))
summary(training)
```


```{r}
## random forrest
library(caret)
set.seed(1235)

library(parallel)
library(doParallel)
cluster <- makeCluster(detectCores() - 1) # convention to leave 1 core for OS
registerDoParallel(cluster)

fitControl <- trainControl(method = "cv",
                           number = 5,
                           allowParallel = TRUE)
## develop training model
fit <- train(classe~., data=training,method="rf",trControl = fitControl,prox=TRUE)
```

## stop cluster
```{r}
stopCluster(cluster)
```

## get model
```{r}
fit
fit$resample
confusionMatrix.train(fit)
fit$finalModel
plot(fit,main="Accuracy by Predictor Count")
varImpPlot(fit$finalModel, main="Variable Importance Plot: Random Forest")
```

## prepare new test cleaned data
```{r}

for (i in 2:53){
	testing[,i]=as.numeric(as.character(testing[,i]))
}

testing$user_name=as.factor(testing$user_name)
```

## Predicting new values

```{r predForest, dependson="centers",fig.height=4,fig.width=4,cache=TRUE}
pred <- predict(fit,testing)
```



